---
name: Update generics

on:  # yamllint disable-line rule:truthy
  push:
    paths:
      - .github/workflows/update-generics.yml
  schedule:
    - cron: "0 * * * *"
  repository_dispatch:
    types:
      - update-generics

jobs:

  update-generics:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: technote-space/create-pr-action@v2
        with:
          EXECUTE_COMMANDS: |
            mkdir .tmp
            git clone --depth=1 https://github.com/23technologies/generics.git .tmp/generics
            bash .tmp/generics/scripts/copy.sh
            rm -rf .tmp
          COMMIT_EMAIL: 'bot@23technologies.cloud'
          COMMIT_MESSAGE: |
            chore: update generics
            Signed-off-by: 23 Technologies Bot <bot@23technologies.cloud>
          COMMIT_NAME: '23 Technologies Bot'
          ONLY_DEFAULT_BRANCH: true
          PR_BRANCH_NAME: 'update-generics'
          PR_BRANCH_PREFIX: 'chore/'
          PR_TITLE: 'chore: update-generics'
